In [17]:
grid = [
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]

In [2]:
import numpy as np

In [3]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


## Version 1

In [4]:
def possible(grid, row, col, num):
    for i in range(9):
        if grid[row][i] == num:
            return False
    for i in range(9):
        if grid[i][col] == num:
            return False
    start_row = row - row % 3
    start_col = col - col % 3
    for i in range(3):
        for j in range(3):
            if grid[start_row+i][start_col + j] == num:
                return False
    return True

In [5]:
possible(grid, 4,4,5)

True

In [6]:
possible(grid, 4,4,3)

False

In [9]:

N = 9
def solve(grid, row, col):
    # If we reach the 8th row and 9th column to stop backtracking
    if row == N - 1 and col == N:
        return True
    
    # Move to the next row after reaching the 9th column
    if col == N:
        row += 1
        col = 0
        
    if grid[row][col] > 0:
        return solve(grid, row, col + 1)
    for num in range(1,N+1,1):
        if possible(grid, row, col, num):
            grid[row][col] = num
            if solve(grid, row, col + 1):
                return True
        grid[row][col] = 0
    return False
                          

In [10]:
if (solve(grid, 0, 0)):
    print(np.matrix(grid))
else:
    print("no solution")

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [11]:
grid = [[3, 0, 6, 5, 0, 8, 4, 0, 0],
        [5, 2, 0, 0, 0, 0, 0, 0, 0],
        [0, 8, 7, 0, 0, 0, 0, 3, 1],
        [0, 0, 3, 0, 1, 0, 0, 8, 0],
        [9, 0, 0, 8, 6, 3, 0, 0, 5],
        [0, 5, 0, 0, 9, 0, 6, 0, 0],
        [1, 3, 0, 0, 0, 0, 2, 5, 0],
        [0, 0, 0, 0, 0, 0, 0, 7, 4],
        [0, 0, 5, 2, 0, 6, 3, 0, 0]]

In [12]:
if (solve(grid, 0, 0)):
    print(np.matrix(grid))
else:
    print("no solution")

[[3 1 6 5 7 8 4 9 2]
 [5 2 9 1 3 4 7 6 8]
 [4 8 7 6 2 9 5 3 1]
 [2 6 3 4 1 5 9 8 7]
 [9 7 4 8 6 3 1 2 5]
 [8 5 1 7 9 2 6 4 3]
 [1 3 8 9 4 7 2 5 6]
 [6 9 2 3 5 1 8 7 4]
 [7 4 5 2 8 6 3 1 9]]


## Better Version

In [23]:
def is_valid(grid, row, col, k):
    not_in_row = k not in grid[row]
    not_in_column = k not in [grid[i][col] for i in range(9)]
    not_in_box = k not in [grid[i][j] 
                           for i in range(row//3*3, row//3*3+3) 
                           for j in range(col//3*3, col//3*3+3)]
    return not_in_row and not_in_column and not_in_box

In [24]:
def solve(grid, row=0, col=0):
    if row == 9:            # All rows have been filled
        return True
    elif col == 9:          # End of column, so move to first column of next row
        return solve(grid, row+1, 0)
    elif grid[row][col] != 0:   # Already fille, move on to next column
        return solve(grid, row, col+1)
    else:                       # Empty cell, start trying numbers
        for k in range(1,10):
            if is_valid(grid, row, col, k):
                grid[row][col] = k  # Try k in the empty slot and move on to next column
                if solve(grid, row, col+1):
                    return True     # The solution worked
                grid[row][col] = 0  # The solution didn't, so try with another number
        return False        # Nothing worked
                
        

In [28]:
if solve(grid):
    print(np.matrix(grid))
else:
    print("No solution, sorry :-(")

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
